# Compose fileのバージョン指定
version: '3'

# どんなコンテナを立ち上げるか
services:

 # ---------------------------------
 # laravelを動かすコンテナ
 # ---------------------------------
 app:
   # どのポートを開いて繋ぐか。下記はコンテナの80番ポートを開いて、ホストの80番につなぐ
   ports:
     - "80:80"
   # 先ほど作ったDockerfileを使って、コンテナをビルドするという指定
   build: ./docker/app
   # コンテナの名前を指定
   container_name: laravel_app
   # ローカルのディレクトリとコンテナ上のディレクトリのリンクを設定
   # ./src は docker-composer.yml のディレクトリ直下にある src を設定している
   # コンテナが作成されると src ディレクトリからコンテナの /var/www/html にアクセスすることができる
   volumes:
     - ./src:/var/www/html

# ----------------------------------
# MySQLを動かすコンテナ
# ----------------------------------
#  db:
#     # build: ./docker/db
#     # container_name: mypg
#     # volumes:
#     #   - ./docker/db/data:/var/lib/postgresql/data
#     # ports:
#     #   - 5433:5432
#     # environment:
#     #   POSTGRES_USER: admin
#     #   POSTGRES_PASSWORD: admin
#     #   POSTGRES_DB: practice_db
#    # Docker HubからMySQL5.7の公式イメージをダウンロードしてくる指定
#    image: mysql:5.7
#    container_name: laravel_db

#    # コンテナ内の環境変数を指定。環境変数を渡すとビルド時に設定してくれるDockerイメージがあるので、利用の際はDocker Hubのサイトで確認する
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: laravel_db
#      MYSQL_USER: laravel_user
#      MYSQL_PASSWORD: laravel_pass
#      TZ: 'Asia/Tokyo'

#    # 起動時のコマンド
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    # ディレクトリ同期。設定ファイルとMySQLのデータが保存される場所を同期している。コンテナは基本的に起動時に変更されてもコンテナ自体が止まるとデータが消えてしまうため、保存しておきたいものはホストマシンと同期しておく必要がある。
#    volumes:
#      - ./docker/db/data:/var/lib/mysql
#      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#    ports:
#      - 3306:3306

#  pma:
#    container_name: pma
#    image: phpmyadmin/phpmyadmin:5.0
#    depends_on:
#       - db
#    ports:
#       - "8080:80"
#    environment:
#       PMA_HOST: localhost
#       PMA_USER: root
#       PMA_PASSWORD: root

# MySQL
 db:
   container_name: laravel-db
   image: mysql:8.0
   volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
   environment:
     MYSQL_DATABASE: practice
     MYSQL_USER: sample-user
     MYSQL_PASSWORD: hi2mi4i6
     MYSQL_ROOT_PASSWORD: mu7ya9to

  # phpMyAdmin
 pma:
   container_name: pma
   image: phpmyadmin/phpmyadmin:5.0
   depends_on:
      - db
   ports:
      - "8080:80"
   environment:
     PMA_HOST: db
     PMA_USER: root
     PMA_PASSWORD: mu7ya9to
